name: Main Config
version: 1.0.0
schema: v1
models:
  - name: Gemini 3.7 Flash
    provider: gemini
    model: gemini-3.7-flash
    apiKey: AIzaSyAy08GkGWRl-jMDArwZt1X5QoZuaDW_73c
    contextLength: 1000000